### ISSUE TITLE
jekyll css-src js-src

### ISSUE THREAD

**Issue by kzahel** [acgd-learn-the-web/www#1]
Hi, I am trying to deploy your website for use offline with thelastmile.org
I have cloned your www repository and all submodules and run jekyll but there are some missing folders js and css.
I can't find out how main.min.js and main.min.css are generated anywhere, can you point out where that is done?
I tried doing something simple like for f in *.js; do cat $f >>  ../js/main.min.js; done
but I don't think that works correctly.

**Comment by kzahel** [comment]
Nevermind. I see the package.json.
Does github pages run an npm install as well as doing a jekyll build? wow.

**Comment by thomasjbradley** [comment]
Yeah, it is all done through the `package.json` file.

I don't host the website on GitHub Pages anymore because of their build change about 6 months ago—they changed how code-highlighting worked and it was completely incompatible with my code samples. Now the whole website is hosted as a static site on KeyCDN (except the activities which will be moved soon).
